$(document).ready(function() {

alert("Welcome! When visiting this page, be sure to interact with the text. Hover over the text and click on words to discover deeper meaning behind this work of WBLA.");
alert("This page envisions a better and more just world for all of us. Hatred will not be tolerated. ");
alert("Do not click further unless you are willing to use activism to feel empowered and change the world for better!");
alert("Make sure to maximize your window. For best results, use Google Chrome.");
$("#two").hover(function(){
$("#pan").show();
});
$("#first").hover(function(){
$("#tub").show();
});
$("#facade").hover(function(){
$("#jack").show();
});
$("#conceal").hover(function(){
$("#black").show();
});
$("#stigmas").hover(function(){
$("#deh").show();
});
$("#norms").hover(function(){
$("#lizzo").show();
});
$("#happy").click(function(){
$("#happy").append("☺");
});
$("#sad").click(function(){
$("#sad").append("☹");
});
$("#earth").click(function(){
$("#earth").append("🌎");
});
$("#earthtwo").click(function(){
$("#earthtwo").append("🌎");
});
$("#patriarchy").click(function(){
$("#patriarchy").append("change");
});
$("#polarized").hover(function(){
$("#gender").show();
});
$("#straighttwo").hover(function(){
$("#pride").show();
});
$("#all").hover(function(){
$("#emily").show();
});
$("#queer").hover(function(){
$("#stephen").show();
});
$("#joy").hover(function(){
$("#rain").show();
});
$("#world").hover(function(){
$("#current").show();
});
$("#pl").hover(function(){
$("#favs").show();
});
$("#obsolete").click(function(){
$(this).hide();
});
$("#p").hover(function(){
$("#pridepower").show();
});
$("#reveal").hover(function(){
$("#black").hide();
});
$("#activism").hover(function(){
$("#advocacy").show();
});
$("#class").hover(function(){
$("#global").show();
});
$("#cause").hover(function(){
$("#trump").show();
});
$("#causetwo").hover(function(){
$("#trump").show();
});
$("#causethree").hover(function(){
$("#trump").show();
});
$("#causefour").hover(function(){
$("#trump").show();
});
$("#causefive").hover(function(){
$("#trump").show();
});
$("#causesix").hover(function(){
$("#trump").show();
});
$("#causeseven").hover(function(){
$("#trump").show();
});
$("#none").hover(function(){
$("#trump").hide();
});
$("#nonetwo").hover(function(){
$("#trump").hide();
});
$("#natural").hover(function(){
$("#bled").show();
});
$("#comjust").hover(function(){
$("#justice").show();
});
$("#endone").draggable();
$("#endtwo").draggable();
$("#endthree").draggable();
$("#endfour").draggable();
$("#endfive").draggable();
$("#endsix").draggable();
$("#endseven").draggable();
$("#wordone").draggable();
$("#wordtwo").draggable();
$("#wordthree").draggable();
$("#wordfour").draggable();
$("#wordfive").draggable();
$("#wordsix").draggable();
$("#endone").hover(function(){
$("#wordone").show();
});
$("#endtwo").hover(function(){
$("#wordtwo").show();
});
$("#endthree").hover(function(){
$("#wordthree").show();
});
$("#endfour").hover(function(){
$("#wordfour").show();
});
$("#endfive").hover(function(){
$("#wordfive").show();
});
$("#endsix").hover(function(){
$("#wordsix").show();
});

})
